version: '3'

services:
  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /ng-app/node_modules
      - ./client:/ng-app

  api:
    build:
      dockerfile: Dockerfile
      context: ./server
    volumes:
      - /usr/src/app/node_modules
      - ./server:/usr/src/app

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: nginx
    ports:
      - '8760:80'
